# Generated by Django 6.0.5 on 2026-05-25 08:33

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='uploads/apps/portfolios/categories/', verbose_name='Image')),
                ('ctx_bg', models.CharField(blank=True, max_length=150, null=True, verbose_name='Background Color')),
                ('ctx_color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Text Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('sorted_as', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['sorted_as', 'is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to='uploads/apps/categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('sorted_as', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['sorted_as', 'is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/apps/portfolios/images', verbose_name='Image')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('total_elevators', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tổng Số Thang Máy')),
                ('building_floors', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số Tầng Tòa Nhà')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày Bắt Đầu')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Ngày Hoàn Thành')),
                ('status', models.CharField(choices=[('planning', 'Đang Lên Kế Hoạch'), ('ongoing', 'Đang Triển Khai'), ('completed', 'Hoàn Thành'), ('archived', 'Lưu Trữ')], default='completed', max_length=50, verbose_name='Status')),
                ('sorted_as', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True, verbose_name='Featured')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer')),
                ('customer_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_set', to='apps.portfoliocategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['sorted_as', '-is_featured', '-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/apps/portfolios/galleries/', verbose_name='Image')),
                ('sorted_as', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to='apps.portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
                'ordering': ['sorted_as'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/apps/products/image/', verbose_name='Thumbnail')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='uploads/apps/products/pdf/', verbose_name='Báo Giá')),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sức chứa (kg)')),
                ('speed', models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tốc Độ (m/s)')),
                ('height', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chiều Cao Tối Đa (m)')),
                ('power_consumption', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiêu Thụ Điện (kWh/h)')),
                ('energy_saving', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tiết Kiệm Điện (%)')),
                ('warranty', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số Năm Bảo Hành')),
                ('passenger', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lượng Người')),
                ('number_stops', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số Trạm Dừng')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chất Liệu   ')),
                ('door_type', models.IntegerField(blank=True, choices=[(1, 'Cửa trượt đơn'), (2, 'Mở 2 cánh ở giữa'), (3, 'Mở 2 cánh ở bên'), (4, 'Mở 4 cánh ở giữa'), (5, 'Cửa mở bằng tay'), (6, 'Tự động')], default=2, null=True, verbose_name='Loại Cửa')),
                ('base_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Giá Gốc')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Giá Giảm')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('is_vip', models.BooleanField(blank=True, default=False, null=True, verbose_name='High Class')),
                ('is_popular', models.BooleanField(blank=True, default=False, null=True, verbose_name='Popular')),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='New')),
                ('is_bestseller', models.BooleanField(blank=True, default=False, null=True, verbose_name='Bestseller')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Nháp'), ('published', 'Xuất Bản'), ('archived', 'Lưu Trữ')], default='published', max_length=20, null=True, verbose_name='Status')),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True, verbose_name='Featured')),
                ('sorted_as', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_product', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='apps.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['sorted_as', 'is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='products_used',
            field=models.ManyToManyField(blank=True, related_name='portfolio_set', to='apps.product', verbose_name='Sản Phẩm Sử Dụng'),
        ),
        migrations.CreateModel(
            name='ProductFaq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Answer')),
                ('icon', models.CharField(blank=True, help_text="<a target='_blank' href='https://fontawesome.com/search>https://fontawesome.com/search</a>", max_length=100, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('sorted_as', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_set', to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
                ('icon', models.CharField(blank=True, help_text="<a target='_blank' href='https://fontawesome.com/search>https://fontawesome.com/search</a>", max_length=100, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('sorted_as', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_set', to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/apps/products/galleries/', verbose_name='Image')),
                ('sorted_as', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product Galleries',
                'ordering': ['sorted_as'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=200, verbose_name='Reviewer Name')),
                ('reviewer_email', models.EmailField(blank=True, max_length=254, verbose_name='Reviewer Email')),
                ('rating', models.IntegerField(choices=[(1, '1 Sao'), (2, '2 Sao'), (3, '3 Sao'), (4, '4 Sao'), (5, '5 Sao')], verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Lượt Hữu Ích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='apps.product', verbose_name='Sản Phẩm')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['category'], name='apps_portfo_categor_31e0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['city'], name='apps_portfo_city_4da0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='apps_produc_slug_b8a43c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='apps_produc_code_b23378_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='apps_produc_categor_90c4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='apps_produc_product_a23948_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['is_approved'], name='apps_produc_is_appr_6ce936_idx'),
        ),
    ]
