# Generated by Django 6.0.5 on 2026-06-05 18:08

import ckeditor.fields
import django.db.models.deletion
import shared_engine.transcode
import web_engine.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_engine', '0001_initial'),
        ('web_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vi', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug_vi', models.SlugField(unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('summary_vi', models.TextField(blank=True, verbose_name='Summary')),
                ('content_vi', ckeditor.fields.RichTextField(blank=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to=shared_engine.transcode.upload_to('uploads/apps/category/images', date=False), verbose_name='Image')),
                ('is_home', models.BooleanField(default=False, verbose_name='Home')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sorted_as', models.PositiveIntegerField(default=0, verbose_name='Sorting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('site', models.ForeignKey(default=web_engine.utils.default_site_code, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='web_engine.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('name_vi', models.CharField(max_length=200, verbose_name='Name')),
                ('slug_vi', models.SlugField(unique=True, verbose_name='Slug')),
                ('summary_vi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Summary')),
                ('content_vi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('pdf', models.FileField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/apps/product/pdfs', date=False), verbose_name='Pdf')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/apps/product/icons', date=False), verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/apps/product/images', date=False), verbose_name='Thumbnail')),
                ('video', models.FileField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/apps/product/videos', date=False), verbose_name='Video')),
                ('base_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Base Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Sale Price')),
                ('is_vip', models.BooleanField(blank=True, default=False, null=True, verbose_name='High Class')),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='New')),
                ('is_popular', models.BooleanField(blank=True, default=False, null=True, verbose_name='Popular')),
                ('is_bestseller', models.BooleanField(blank=True, default=False, null=True, verbose_name='Bestseller')),
                ('is_home', models.BooleanField(default=False, verbose_name='Home')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sorted_as', models.PositiveIntegerField(default=0, verbose_name='Sorting')),
                ('visited_as', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='apps.category', verbose_name='Category')),
                ('products_used', models.ManyToManyField(blank=True, related_name='product_set', to='site_engine.project', verbose_name='Used Products')),
                ('site', models.ForeignKey(default=web_engine.utils.default_site_code, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='web_engine.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['sorted_as', 'is_active', 'is_home'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_vi', models.CharField(max_length=200, verbose_name='Feature')),
                ('value_vi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
                ('icon_svg', models.TextField(blank=True, null=True, verbose_name='Svg')),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/project/features', date=False), verbose_name='Icon')),
                ('icon_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('icon_code', models.CharField(blank=True, help_text="<a target='_blank' href='https://fontawesome.com/search?o=r&f=brands'>https://fontawesome.com/search?o=r&f=brands</a>", max_length=30, null=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sorted_as', models.PositiveIntegerField(default=0, verbose_name='Sorting')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_set', to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/project/galleries', date=False), verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sorted_as', models.PositiveIntegerField(default=0, verbose_name='Sorting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
    ]
