# Generated by Django 6.0.5 on 2026-05-25 17:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=200, verbose_name='Alias')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='Icon')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/apps/products/image/', verbose_name='Thumbnail')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True, verbose_name='Featured')),
                ('sorted_as', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['sorted_as', 'is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
                ('icon', models.CharField(blank=True, help_text="<a target='_blank' href='https://fontawesome.com/search>https://fontawesome.com/search</a>", max_length=100, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('sorted_as', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_set', to='apps.solution', verbose_name='Solution')),
            ],
            options={
                'verbose_name': 'Solution Feature',
                'verbose_name_plural': 'Solution Features',
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
    ]
