# Generated by Django 6.0.5 on 2026-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='meta_description',
            new_name='meta_description_vi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_keywords',
            new_name='meta_keywords_vi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_title',
            new_name='meta_title_vi',
        ),
        migrations.AlterField(
            model_name='product',
            name='summary_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
