# Generated by Django 6.0.5 on 2026-06-05 18:57

import django.core.validators
import shared_engine.transcode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacity (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='door_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Cửa trượt đơn'), (2, 'Mở 2 cánh ở giữa'), (3, 'Mở 2 cánh ở bên'), (4, 'Mở 4 cánh ở giữa'), (5, 'Cửa mở bằng tay'), (6, 'Tự động')], default=2, null=True, verbose_name='Elevator Door Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_saving',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Electricity Savings (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Height (m)'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Elevator Materials'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_stops',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Stops'),
        ),
        migrations.AddField(
            model_name='product',
            name='passenger',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of People'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_consumption',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Electricity Consumption (kWh/h)'),
        ),
        migrations.AddField(
            model_name='product',
            name='speed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Speed \u200b\u200b(m/s)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Years of Warranty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Bestseller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='High Class'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/apps/product/features', date=False), verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared_engine.transcode.upload_to('uploads/apps/product/galleries', date=False), verbose_name='Image'),
        ),
    ]
