# Generated by Django 6.0.5 on 2026-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_solution_solutionfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.TextField()),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(blank=True, default=True, null=True, verbose_name='Featured')),
                ('sorted_as', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
    ]
