# Generated by Django 6.0.5 on 2026-06-06 14:38

import django.db.models.deletion
import web_engine.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_meta_description_product_meta_description_vi_and_more'),
        ('web_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='site',
            field=models.ForeignKey(default=web_engine.utils.default_site_code, on_delete=django.db.models.deletion.CASCADE, related_name='category_app', to='web_engine.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='apps.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.ForeignKey(default=web_engine.utils.default_site_code, on_delete=django.db.models.deletion.CASCADE, related_name='product_app', to='web_engine.site', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='ProductFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Answer')),
                ('icon', models.CharField(blank=True, help_text="<a target='_blank' href='https://fontawesome.com/search>https://fontawesome.com/search</a>", max_length=100, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sorted_as', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sorting')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_set', to='apps.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'ordering': ['sorted_as', 'is_active'],
            },
        ),
    ]
