# Generated by Django 6.0.5 on 2026-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('planning', 'Đang Lên Kế Hoạch'), ('ongoing', 'Đang Triển Khai'), ('completed', 'Hoàn Thành')], default='completed', max_length=50, verbose_name='Status'),
        ),
    ]
