# Generated by Django 6.0.5 on 2026-06-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_category_site_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfaq',
            old_name='answer',
            new_name='answer_vi',
        ),
        migrations.RenameField(
            model_name='productfaq',
            old_name='question',
            new_name='question_vi',
        ),
    ]
