# Generated by Django 6.0.5 on 2026-05-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_portfolio_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliocategory',
            old_name='ctx_bg',
            new_name='color_bg',
        ),
        migrations.RenameField(
            model_name='portfoliocategory',
            old_name='ctx_color',
            new_name='color_color',
        ),
    ]
