# Generated by Django 6.0.5 on 2026-06-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_answer_productfaq_answer_vi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='cabin_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cabin Materials'),
        ),
    ]
