# Generated by Django 6.0.5 on 2026-05-30 08:09

import shared_engine.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_ctx_bg_portfoliocategory_color_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared_engine.upload.upload_to('uploads/apps/portfolios/images', date=False), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=shared_engine.upload.upload_to('uploads/apps/portfolios/categories', date=False), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='image',
            field=models.ImageField(upload_to=shared_engine.upload.upload_to('uploads/apps/portfolios/galleries', date=False), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared_engine.upload.upload_to('uploads/apps/products/images', date=False), verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=shared_engine.upload.upload_to('uploads/apps/products/pdfs', date=False), verbose_name='Báo Giá'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=shared_engine.upload.upload_to('uploads/apps/categories', date=False), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared_engine.upload.upload_to('uploads/apps/products/galleries', date=False), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shared_engine.upload.upload_to('uploads/apps/products/images', date=False), verbose_name='Thumbnail'),
        ),
    ]
