# Generated by Django 6.0.5 on 2026-05-31 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_portfolio_image_alter_portfoliocategory_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['sorted_as', '-is_featured', '-completion_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['sorted_as', 'is_active', 'name'], 'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='portfoliogallery',
            options={'ordering': ['sorted_as'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='sorted_as',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sorted_as',
            field=models.PositiveIntegerField(default=0, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='sorted_as',
            field=models.IntegerField(default=0, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to='apps.portfolio', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='sorted_as',
            field=models.IntegerField(default=0, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sorted_as',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sorted_as',
            field=models.IntegerField(default=0, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='sorted_as',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='sorted_as',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='sorted_as',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sorted_as',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sorting'),
        ),
        migrations.AlterField(
            model_name='solutionfeature',
            name='sorted_as',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sorting'),
        ),
    ]
