version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app_net
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/project/staticfiles
      - media_volume:/app/project/media
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - app_net
    command: sh -c "gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    # command: sh -c "python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - app_net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

networks:
  app_net:

volumes:
  mysql_data:
  static_volume:
  media_volume: