ALTER TABLE cms_engine_page
ADD COLUMN is_contact BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE cms_engine_page
ADD COLUMN is_privacy_policy BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE cms_engine_page
ADD COLUMN is_terms_of_use BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE cms_engine_page
ADD COLUMN is_archive BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE cms_engine_page
ADD COLUMN is_snippet BOOLEAN NOT NULL DEFAULT FALSE;