"""
Django settings for project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation  import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j)w)+b=001(jtrzc5v@iotv*bt0ifszt)!9c7d85pasikx2iol'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("APP_DEBUG", "False") == "True"

if DEBUG:
    print("Your http server is running on DEBUG mode....")

# Application definition
SITE_ID = int(os.getenv('SITE_ID', '1'))
SITE_CODE = os.getenv('SITE_CODE', 'HQT_ELEVATOR')
SITE_HOST = os.getenv('SITE_HOST', '127.0.0.1')
SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'localhost')
SITE_DEBUG = DEBUG or SITE_DOMAIN == 'localhost'


# Django definition
TEMPLATE_DEBUG = SITE_DEBUG
THUMBNAIL_DEBUG = SITE_DEBUG
USE_X_FORWARDED_HOST = True
CSRF_COOKIE_SECURE = not SITE_DEBUG
SESSION_COOKIE_SECURE = not SITE_DEBUG
SECURE_SSL_REDIRECT = not SITE_DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
X_FRAME_OPTIONS = 'SAMEORIGIN'
CSRF_TRUSTED_ORIGINS = [f"http://{SITE_DOMAIN}", f"https://{SITE_DOMAIN}"]
ALLOWED_HOSTS = [SITE_HOST, SITE_DOMAIN, f"www.{SITE_DOMAIN}", "localhost", "127.0.0.1", "0.0.0.0"]
INTERNAL_IPS = ALLOWED_HOSTS # debug_toolbar

INSTALLED_APPS = [
    # 'mailer',
    'grappelli.dashboard',
    'grappelli',
    'filebrowser',
    'ckeditor',
    'smart_selects',
    'captcha',
    'sorl.thumbnail',
    'debug_toolbar',

    # Core Library
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cms_engine',
    'cms_app',

    # Lib Engine
    'recruitment_engine',
    
    # App Engine
    'project.apps',
    'project.apps.create_default_apps', ## --> FOR FIRST INSTALL
]

MIDDLEWARE = [
    'cms_engine.middleware.RedirectionMiddleware',
    'cms_engine.middleware.ResolverMiddleware',
    # 'cms_engine.middleware.MultipleProxyMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'cms_engine.context_processors.session',
                'cms_engine.context_processors.backoffice',
                'project.context.default_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        "HOST": os.getenv('DB_HOST', '127.0.0.1'),
        "NAME": os.getenv('DB_NAME', 'hqt_elevator'),
        "USER": os.getenv('DB_USER', 'root'),
        "PASSWORD": os.getenv('DB_PASSWORD', 'dev_only_pwd'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'vi-vn'
LANGUAGES = [
    # ('en', _('English')),
    ('vi', _('Vietnamese')),
]

DATETIME_FORMAT = "d/m/Y H:i"
DATE_FORMAT = "d/m/Y"
TIME_FORMAT = "H:i"

USE_I18N = True
USE_L10N = True
USE_TZ = True
USE_TM = True

TIME_ZONE = 'UTC'
LOCALE_PATHS = []

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (upload/user generated)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# FileBrowser uploads
FILEBROWSER_DIRECTORY = 'uploads/'

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # 'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_EXTRA_PLUGINS = []
if os.getenv("OPENAI_API_KEY", ""):
    CKEDITOR_EXTRA_PLUGINS.append('openai')
if os.getenv("GEMINI_API_KEY", ""):
    CKEDITOR_EXTRA_PLUGINS.append('gemini')
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': ','.join(CKEDITOR_EXTRA_PLUGINS),
    },
}

# We added new administration (grappelli)
GRAPPELLI_INDEX_DASHBOARD = 'project.dashboard.CustomIndexDashboard'
GRAPPELLI_ADMIN_TITLE = "Administrator"
# GRAPPELLI_SWITCH_USER = True

LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, './logs/debug.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'] if DEBUG else ['file'],
            'level': os.getenv('SITE_LOG_LEVEL', 'ERROR'),
            'propagate': True,
        },
    },
}

# We added cache
# CACHES = {
    # 'default': {
        # 'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        # 'LOCATION': os.getenv('MEMO_CACHE_LOCATION', '127.0.0.1:11211'),
    # },
    # 'redis': {
        # 'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        # 'LOCATION': os.getenv('REDIS_CACHE_LOCATION'),
    # },
# }

# We added session
# SESSION_ENGINE = os.getenv('REDIS_SESSION_ENGINE', 'redis_sessions.session')
# SESSION_REDIS_HOST = os.getenv('REDIS_SESSION_HOST', '127.0.0.1')
# SESSION_REDIS_PORT = os.getenv('REDIS_SESSION_PORT', 6379)
# SESSION_REDIS_DB = os.getenv('REDIS_SESSION_DB', 0) 
# SESSION_COOKIE_AGE = os.getenv('REDIS_SESSION_COOKIE_AGE', 3600)

# We added email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-server')  # SMTP server host
EMAIL_PORT = os.getenv('EMAIL_PORT', 587)  # SMTP server port (587 for TLS, 465 for SSL)
EMAIL_USE_TLS = True  # True for TLS, False for SSL
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # SMTP server username
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # SMTP server password
EMAIL_USE_SSL = False  # Set to True if using SSL
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')  # Default sender email address
DEFAULT_NOTIFY_EMAIL = os.getenv('DEFAULT_NOTIFY_EMAIL', '')  # Custom notify email address
DEFAULT_MARKETING_EMAIL = os.getenv('DEFAULT_MARKETING_EMAIL', '')  # Custom newsletter email address


if not DEBUG:
    LOCALE_PATHS.append(BASE_DIR / "locale")